# Generated by Django 4.2.6 on 2024-01-27 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlogin",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
