# Generated by Django 4.2.6 on 2023-11-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlogin",
            name="password",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userlogin",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
