# Generated by Django 4.2.6 on 2023-12-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_alter_userlogin_password_alter_userlogin_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                # ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
