# Generated by Django 4.2.6 on 2023-12-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0004_rename_password_userlogin_firstname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlogin",
            name="mobilenumber",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userlogin",
            name="password",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userlogin",
            name="username",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userlogin",
            name="firstname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userlogin",
            name="lastname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
