# Generated by Django 4.2.6 on 2023-12-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0006_alter_userlogin_mobilenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlogin",
            name="mobilenumber",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
