# Generated by Django 4.2.6 on 2023-12-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0007_alter_userlogin_mobilenumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="userdocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf", models.FileField(blank=True, null=True, upload_to="pdf/")),
                ("image", models.ImageField(blank=True, null=True, upload_to="image/")),
            ],
        ),
        # migrations.DeleteModel(
        #     name="MyModels",
        # ),
        # migrations.AddField(
        #     model_name="userlogin",
        #     name="image",
        #     field=models.ImageField(blank=True, null=True, upload_to="images/"),
        # ),
    ]
