# Generated by Django 4.2.6 on 2023-12-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0008_userdocuments_delete_mymodels_userlogin_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlogin",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
