# Generated by Django 5.0.1 on 2024-01-31 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_userlogin_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='image',
            new_name='Background_image',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='Profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='userimages/'),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 31, 17, 48, 57, 623716), null=True),
        ),
    ]
