# Generated by Django 5.0.1 on 2024-02-05 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_userlogin_aboutme_userlogin_address_userlogin_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='postalcode',
            new_name='pincode',
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 5, 21, 1, 7, 592528), null=True),
        ),
    ]
