# Generated by Django 5.0.1 on 2024-02-14 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_alter_userlogin_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attendence',
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 14, 16, 30, 48, 752227), null=True),
        ),
    ]
