# Generated by Django 5.0.1 on 2024-02-14 11:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_delete_attendence_alter_userlogin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 14, 16, 31, 19, 672450), null=True),
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_in_at', models.TimeField()),
                ('log_out_at', models.TimeField()),
                ('userlogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userlogin')),
            ],
        ),
    ]
