# Generated by Django 5.0.1 on 2024-02-15 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_alter_userlogin_created_at_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 15, 14, 3, 49, 558472), null=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.CharField(blank=True, default='Asdf@123', max_length=50, null=True),
        ),
    ]
