# Generated by Django 5.0.1 on 2024-02-16 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_alter_userlogin_options_alter_userlogin_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 16, 11, 58, 32, 583667), null=True),
        ),
    ]
