# Generated by Django 5.0.1 on 2024-03-04 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_remove_userlogin_email_remove_userlogin_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailotp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 18, 7, 1, 82027), null=True),
        ),
    ]
