# Generated by Django 5.0.1 on 2024-03-23 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_alter_userlogin_created_at_attendence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='userlogin',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 23, 12, 12, 10, 993968), null=True),
        ),
    ]
