# Generated by Django 4.2.11 on 2024-05-08 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0028_rename_log_in_at_attendence_login_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlogin",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 5, 8, 5, 58, 30, 542600),
                null=True,
            ),
        ),
    ]
