# Generated by Django 4.2.11 on 2024-05-08 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0029_alter_userlogin_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlogin",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 5, 8, 6, 6, 56, 315854, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
